services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17.2
    hostname: postgres-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
